### ISSUE TITLE
Ruby docs

### ISSUE THREAD

**Issue by jihwan1ua** [401ChemistryGenealogy/ChemistryGenealogy#34]
Btw, we need ruby docs.

When I did some search, seems like there is a tool for creating ruby docs automatically.

We just need to install in gem.

**Comment by slmyers** [comment]
> Documentation [0/10]
> 
> No language documentation (automatically generated documentation) was found in team's repository. (Please let us know if you had that somewhere)

I'll take care of this I guess.

**Comment by slmyers** [comment]
```
gem install yard
cd /backend
yardoc 'app/**/*.rb'
```

output is in /backend/doc
