### ISSUE TITLE
Project roles

### ISSUE THREAD

**Issue by jihwan1ua** [401ChemistryGenealogy/ChemistryGenealogy#5]
Guys please tell where are you going to be working on, whether front-end or back-end.
And please when you are working on something like controller where you would need to go front-end and back-end alternatively, then let those people in their part know so the works are not being duplicated.
On the comment below, leave your roles whether its front-end or back-end.

**Comment by jihwan1ua** [comment]
I'm going to be working on the back-end

**Comment by slmyers** [comment]
I'm doing frontend + backend
